languageCode = "zh-HK"
title = "昆特牌教學"

theme = "hugo-theme-relearn"

enableRobotsTXT = true

[services]
[services.googleAnalytics]
ID = 'G-39JNMJPK4V'

[outputs]
home = ["HTML", "RSS", "SEARCH"]

[params]
disableLandingPageButton = true
# Disabled because it is not working correctly with Chinese characters.
disableSearch = true
author.name = "Reguna"
description = "Guide for GWENT: The Witcher Card Game, written in Cantonese."

themeVariant = "relearn-dark"

[[menu.shortcuts]]
name = "<i class='fa fa-comments'></i> 最新LIHKG貼文（17）"
url = "https://lih.kg/2844269"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-network-wired'></i> 相關網站"
url = "https://regunakyle.github.io/lihkg-gwent-guide/others/#其他相關網站"
weight = 21

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github"
url = "https://github.com/regunakyle/lihkg-gwent-guide/"
weight = 22
