baseURL = "https://regunakyle.github.io/LIHKG-Gwent-guide/"
languageCode = "zh-HK"
title = "LIHKG Gwent Guide"

theme = "hugo-theme-relearn"

publishDir = "docs"

[outputs]
    home = [ "HTML", "RSS", "JSON"]

[params]
    custom_css = ["css/custom.css"]
    disableLandingPageButton = true
    # Disabled because it is not working correctly with Chinese characters.
    disableSearch = true

[[menu.shortcuts]] 
name = "<i class='fa fa-comments'></i> 最新LIHKG貼文（15）"
url = "https://lih.kg/2449224"
weight = 20

#todo
[[menu.shortcuts]] 
name = "<i class='fas fa-network-wired'></i> 相關網站"
url = "https://regunakyle.github.io/LIHKG-Gwent-guide/others/#其他相關網站"
weight = 21

[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github"
url = "https://github.com/regunakyle/LIHKG-Gwent-guide/"
weight = 22
